# Generated by Django 4.2.3 on 2023-08-21 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_entries_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
