# Generated by Django 4.2.3 on 2023-09-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_new_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='highestbiduser',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
