# Generated by Django 4.2.3 on 2023-09-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_closed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='closed',
            new_name='closed_entries',
        ),
    ]
