# Generated by Django 4.2.3 on 2023-09-20 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_closed_closed_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
