# Generated by Django 4.2.3 on 2023-09-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_watchlist',
            name='user',
        ),
    ]
