# Generated by Django 4.2.3 on 2023-09-20 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_user_watchlist_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_watchlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
