# Generated by Django 4.2.3 on 2023-09-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_user_watchlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
